### ISSUE TITLE
Mobile and Web View

### ISSUE THREAD

**Issue by acegacusan** [cabreragran/buschase#36]
How to disable Web View for Conductor since conductor can only access his part through mobile. 

-Additional-
How to limit layout or data that will be displayed in mobile and web.

**Comment by earmix** [comment]
**hidden-lg** for large screen
**hidden-md** for medium screen
**hidden-sm** for tablets
**hidden-xs** for mobile

**reference**
http://www.w3schools.com/bootstrap/bootstrap_ref_css_helpers.asp

**Comment by earmix** [comment]
if hidden on a certain screen size. create a message for user to be notified

example:
if hidden on large and medium screen. "This page could only be viewed on mobile devices"
