### ISSUE TITLE
Ui Suggestion. Bussers Theme. HAHAHA

### ISSUE THREAD

**Issue by earmix** [cabreragran/buschase#52]
[Passenger Control.svg.zip](https://github.com/cabreragran/buschase/files/482541/Passenger.Control.svg.zip)

`<svg viewBox="0 0 320 568" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414">
    <clipPath id="a">
        <path d="M0 0h320v568H0z"/>
    </clipPath>
    <g clip-path="url(#a)">
        <path fill="#ffd300" d="M0 0h320v568H0z"/>
        <g font-family="&apos;Arial-Black&apos;,&apos;Arial Black&apos;,sans-serif" font-weight="900">
            <text x="220.935" y="458.747" font-size="24">
                S
                <tspan x="237.307px 247px 262.048px 271.74px 286.788px 300.488px" y="458.747px 458.747px 458.747px 458.747px 458.747px 458.747px">tatus:</tspan>
            </text>
            <text x="192.966" y="491.946" font-size="36">
                a
                <tspan x="215.538px 238.11px 252.648px 263.197px 283.747px" y="491.946px 491.946px 491.946px 491.946px 491.946px">ctive</tspan>
            </text>
        </g>
        <g font-family="&apos;Arial-Black&apos;,&apos;Arial Black&apos;,sans-serif" font-weight="900">
            <text x="11.383" y="492.385" font-size="36">
                A
                <tspan x="37.945px 64.507px 89.065px 111.637px 134.208px" y="492.385px 492.385px 492.385px 492.385px 492.385px">YT420</tspan>
            </text>
            <text x="10.272" y="458.801" font-size="24">
                B
                <tspan x="27.98px 43.028px 56.728px 75.76px 90.808px" y="458.801px 458.801px 458.801px 458.801px 458.801px">usNo.</tspan>
            </text>
        </g>
        <g font-family="&apos;Arial-Black&apos;,&apos;Arial Black&apos;,sans-serif" font-weight="900">
            <text x="49.733" y="133.659" font-size="16">
                f
                <tspan x="55.159px 61.719px 71.591px" y="133.659px 133.659px 133.659px">ree</tspan>
            </text>
            <text x="9.875" y="133.32" font-size="24">
                0
                <tspan x="24.683" y="133.32">8</tspan>
            </text>
            <text x="48.756" y="110.894" font-size="16">
                p
                <tspan x="58.628px 63.156px 72.755px 82.627px 92.498px" y="110.894px 110.894px 110.894px 110.894px 110.894px">ickup</tspan>
            </text>
            <text x="9.375" y="110.407" font-size="24">
                0
                <tspan x="24.183" y="110.407">2</tspan>
            </text>
            <g>
                <text x="48.186" y="87.775" font-size="16">
                    o
                    <tspan x="58.058px 67.93px 77.802px 87.673px 97.545px 104.245px" y="87.775px 87.775px 87.775px 87.775px 87.775px 87.775px">nboard</tspan>
                </text>
                <text x="9.875" y="87.935" font-size="24">
                    4
                    <tspan x="24.683" y="87.935">0</tspan>
                </text>
            </g>
            <text x="8.898" y="63.391" font-size="16">
                passenger
                <tspan x="99.977px 109.75px" y="63.391px 63.391px">s:</tspan>
            </text>
        </g>
        <text x="60.039" y="33.225" font-family="&apos;Arial-Black&apos;,&apos;Arial Black&apos;,sans-serif" font-weight="900" font-size="30">MENU</text>
        <path d="M9.5 8.5H55V15H9.5zM9.5 18.5H55V25H9.5zM9.5 28.5H55V35H9.5z"/>
        <g>
            <circle cx="160" cy="284" r="149.25"/>
            <path d="M293.137 289.25c-2.743 71.107-61.349 128-133.137 128-71.788 0-130.394-56.893-133.137-128h266.274z" fill="#ffd300"/>
            <text x="107.326" y="370.21" font-family="&apos;Arial-Black&apos;,&apos;Arial Black&apos;,sans-serif" font-weight="900" font-size="20">
                p
                <tspan x="119.866px 132.406px 143.822px 155.239px 167.779px 180.319px 192.859px 205.399px" y="370.21px 370.21px 370.21px 370.21px 370.21px 370.21px 370.21px 370.21px">assenger</tspan>
            </text>
            <text x="82.442" y="355.868" font-family="&apos;Arial-Black&apos;,&apos;Arial Black&apos;,sans-serif" font-weight="900" font-size="36">
                S
                <tspan x="107px 129.572px 152.144px 166.682px 181.836px 204.408px 226.979px" y="355.868px 355.868px 355.868px 355.868px 355.868px 355.868px 355.868px">ubtract</tspan>
            </text>
            <g>
                <path d="M26.863 278.75c2.743-71.107 61.349-128 133.137-128 71.788 0 130.394 56.893 133.137 128H26.863z" fill="#ffd300"/>
                <text x="106.925" y="231.71" font-family="&apos;Arial-Black&apos;,&apos;Arial Black&apos;,sans-serif" font-weight="900" font-size="20">
                    p
                    <tspan x="119.465px 132.005px 143.422px 154.838px 167.378px 179.918px 192.458px 204.998px" y="231.71px 231.71px 231.71px 231.71px 231.71px 231.71px 231.71px 231.71px">assenger</tspan>
                </text>
                <text x="126.313" y="217.368" font-family="&apos;Arial-Black&apos;,&apos;Arial Black&apos;,sans-serif" font-weight="900" font-size="36">
                    A
                    <tspan x="152.875px 175.798px" y="217.368px 217.368px">dd</tspan>
                </text>
            </g>
            <g>
                <path d="M23.5 268.443h273v39.784h-273z"/>
                <text x="57.608" y="299.864" font-family="&apos;Arial-Black&apos;,&apos;Arial Black&apos;,sans-serif" font-weight="900" font-size="32.925" fill="#fff">
                    KED
                    <tspan x="161.848" y="299.864">C</tspan>
                </text>
            </g>
        </g>
        <g>
            <text x="209.5" y="95.101" font-family="&apos;Arial-Black&apos;,&apos;Arial Black&apos;,sans-serif" font-weight="900" font-size="36">42</text>
            <text x="268.634" y="113.015" font-family="&apos;Arial-Black&apos;,&apos;Arial Black&apos;,sans-serif" font-weight="900" font-size="30">
                5
                <tspan x="287.144" y="113.015">0</tspan>
            </text>
            <text x="257.945" y="127.172" font-family="&apos;Arial-Black&apos;,&apos;Arial Black&apos;,sans-serif" font-weight="900" font-size="16">
                sea
                <tspan x="288.789px 295.891px" y="127.172px 127.172px">ts</tspan>
            </text>
            <path d="M289.778 72.399l-3.068-3.068-35.728 35.728 3.068 3.068 35.728-35.728z"/>
            <text x="225.578" y="63.391" font-family="&apos;Arial-Black&apos;,&apos;Arial Black&apos;,sans-serif" font-weight="900" font-size="16">
                city:
                <tspan x="247.078px 257.75px" y="63.391px 63.391px">pa</tspan>
            </text>
            <path d="M305.684 171l-36.25-36.25h36.25V171z" fill="#080700"/>
        </g>
        <g>
            <path d="M12.041 516h294.997v41.5H12.041z"/>
            <text x="73.476" y="545.57" font-family="&apos;Arial-Black&apos;,&apos;Arial Black&apos;,sans-serif" font-weight="900" font-size="24" fill="#fff">
                E
                <tspan x="89.848px 108.88px 126.588px 133.632px 150.004px 166.376px 182.748px 199.12px 207.5px 226.532px" y="545.57px 545.57px 545.57px 545.57px 545.57px 545.57px 545.57px 545.57px 545.57px 545.57px">ND SESSION</tspan>
            </text>
        </g>
    </g>
</svg>`

**Comment by acegacusan** [comment]
AK okay yan. pero kaya mo tanggalin mga value? Bus number, Active, End Session. para malagyan ng label nalang. and try ko gawin ayusin yung svg as button

**Comment by earmix** [comment]
pwede maalis yun. nasa loob ng <text></text> tag yung mga text na yan. palitan mo nalang ng $scope. para naman sa button css style. gamit ka pseudo class. a:hover. lagyan mo nalang ng class name yung mga <g></g> tapos palitan ibang values. hahaha

**Comment by acegacusan** [comment]
sige men. after ko sa reports </3 kung maihabol ko yan (Y)

**Comment by earmix** [comment]
sige2. haha
